apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-managed
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/maor-klir/homelab-2
