apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: argo-cd
    releaseName: argocd
    version: 8.2.3
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    valuesFile: values.yaml