configs:
  cm:
    kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"
    url: "https://argocd.cloudandklir.com"

crds:
  install: true
  # Keep CRDs on chart uninstall
  keep: false